"""PLATE Greensboro restaurant dataset.

Original student records are retained with their *historical, unverified* 1–5
price scores and ratings. Later listings have None for unknown prices and
ratings. None must NOT be represented as zero or five stars.
Records: [cuisine, name, price_score, rating, address]. Append only: the frontend
stores favorites by row index, so never reorder or delete rows in place.
listing_sources maps each added listing to where it came from. The first batch
was checked against downtown/visitor directories; the rest come from
OpenStreetMap via tools/find_restaurants.py (ODbL, "© OpenStreetMap
contributors") and are not individually verified.
"""
types = ['african',
 'american',
 'barbecue',
 'breakfast',
 'cafe',
 'caribbean',
 'chinese',
 'czech',
 'french',
 'german',
 'indian',
 'italian',
 'japanese',
 'korean',
 'latin',
 'mediterranean',
 'mexican',
 'peruvian',
 'pizza',
 'seafood',
 'thai',
 'vegetarian',
 'vietnamese']

restaurant_data = [['american', 'Liberty Oak', '4', '4', '100 W Washington St'],
 ['japanese', 'Sushi Republic', '2', '4.5', '329 Tate St'],
 ['mediterranean', 'Sarahs Kabob Shop', '5', '5', '5340 W Market St'],
 ['mexican', 'Crafted - The Art of the Taco', '2', '4.5', '219 S Elm St'],
 ['pizza', 'Crafted - The Art of Pizza', '2', '4.5', '220 South Elm Street'],
 ['american', '1618 Downtown', '4.6', '3', '312 Elm St'],
 ['french', 'Print Works Bistro', '4.6', '4', '702 Green Valley Road'],
 ['american', 'Crafted - The Art of Street Food', '4.6', '2', '220 South Elm Street'],
 ['american', 'Lindley Park Filling Station', '4.6', '2', '2201 Walker Ave'],
 ['american', "Dame's Chicken & Waffles", '4.6', '1', '301 Martin Luther King Jr Dr'],
 ['american', "B. Christopher's Steakhouse", '4.5', '4', '201 North Elm Street'],
 ['mediterranean', 'Green Valley Grill', '4.5', '4', '622 Green Valley Road'],
 ['barbecue', 'Stamey’s Barbecue', '4.6', '3', '2812 Battleground Ave'],
 ['american', 'Hops Burger Bar', '4.6', '3', '2419 Spring Garden St'],
 ['thai', 'Taste of Thai', '4.4', '2', '1500 Mill St Ste 104'],
 ['indian', 'Dhanraj Emanuel Restaurant', '4.6', '2', '324 S Elm St'],
 ['italian', 'Osteria Italian Restaurant', '4.6', '4', '1310 Westover Ter Ste 111'],
 ['chinese', 'Phoenix Asian Cuisine', '4.3', '2', '1641 New Garden Rd Ste 111'],
 ['american', 'Emma Key’s Flat-Top Grill', '4.5', '2', '2206 Walker Ave'],
 ['cafe', 'Green Bean', '4.6', '2', '341 S Elm St'],
 ['american', 'Iron Hen Cafe', '4.5', '3', '908 Cridland Rd'],
 ['american', 'Darryls Wood Fired Grill', '4.6', '4', '3300 High Point Rd'],
 ['italian', 'Villa Rosa Italian Restaurant', '4.5', '3', '6019 W Market St'],
 ['american', 'The Old Town Draught House', '4.5', '2', '1205 Spring Garden St'],
 ['barbecue', 'Country BBQ', '4.4', '2', '4012 W Wendover Ave'],
 ['chinese', 'PF Chang’s', '4.4', '3', '3338 W Friendly Ave'],
 ['american', 'Biscuitville', '4.3', '1', '3011 Spring Garden St'],
 ['mexican', 'El Camino Real Mexican Grill', '4.3', '2', '413 Pisgah Church Rd'],
 ['korean', 'Bonchon Greensboro', None, None, '607 S Elm St'],
 ['korean', 'Seoul Garden Restaurant', None, None, '5318 W Market St Ste C'],
 ['korean', 'KPOT Korean BBQ & Hot Pot', None, None, '3011 W Gate City Blvd'],
 ['vietnamese', 'Pho Hien Vuong Vietnamese Restaurant', None, None, '4109 Spring Garden St'],
 ['vietnamese', 'Saigon Cuisine Restaurant', None, None, '4205 W Gate City Blvd'],
 ['vietnamese', 'Banh Mi Saigon Vietnamese Sandwiches', None, None, '3808 W Gate City Blvd'],
 ['vietnamese', 'JakJin Bistro Pho & More', None, None, '4414 Lawndale Dr Ste F'],
 ['indian', 'Saffron Indian Cuisine', None, None, '1500 Mill St Ste 104'],
 ['indian', 'Raaz Indian Kitchen', None, None, '427 Tate St'],
 ['indian', 'Agni Indian Restaurant and Bar', None, None, '651 S Regional Rd'],
 ['thai', 'Bangkok Cafe', None, None, '1203 S Holden Rd'],
 ['mediterranean', 'Jerusalem Market on Elm', None, None, '310 S Elm St'],
 ['mediterranean', 'Zaytoon Mediterranean Grill', None, None, '114 N Elm St'],
 ['mediterranean', "Aladdin's Shawarma", None, None, '5103 W Market St Ste A'],
 ['peruvian', 'Inka Peruvian Grill', None, None, '214 S Elm St'],
 ['french', 'Chez Genèse', None, None, '616 S Elm St'],
 ['american', 'Blue Denim', None, None, '217 S Elm St'],
 ['american', 'Undercurrent Restaurant', None, None, '327 Battleground Ave'],
 ['american', 'White and Wood', None, None, '215 S Elm St'],
 ['american', 'Machete', None, None, '600C Battleground Ave'],
 ['american', 'The Sage Mule', None, None, '608 Battleground Ave'],
 ['american', "Dear Dad's", None, None, '219 S Elm St'],
 ['american', 'Natty Greene’s Pub & Brewing Co.', None, None, '345 S Elm St'],
 ['japanese', 'Yokai', None, None, '501 N Greene St'],
 ['japanese', "Midori's Japanese Hibachi", None, None, '114 N Elm St'],
 ['pizza', 'Mellow Mushroom', None, None, '609 S Elm St'],
 ['cafe', 'Chandler’s', None, None, '341 S Elm St'],
 ['cafe', 'Awoo Coffee', None, None, '236 S Elm St'],
 ['american', 'Pangaea Bistro & Bar', None, None, '230 S Elm St'],
 ['american', 'CharBar No. 7', None, None, '3724 Lawndale Dr'],
 ['seafood', '1618 West Seafood Grille', None, None, '1618 West Friendly Avenue'],
 ['cafe', '33 & Elm Coffee House', None, None, '924 West Gate City Boulevard'],
 ['seafood', '42 Fry', None, None, '815 West Gate City Boulevard'],
 ['cafe', '7 Brew', None, None, '2420 Battleground Avenue'],
 ['cafe', 'A Special Blend', None, None, '3900 West Market Street Ste C'],
 ['mediterranean', 'Achilles Grill', None, None, '2301 Battleground Avenue'],
 ['mediterranean', 'Acropolis', None, None, '416 North Eugene Street'],
 ['cafe', 'Akoko', None, None, '3821 West Gate City Boulevard Ste E'],
 ['chinese', 'Apple China', None, None, '5710 West Gate City Boulevard'],
 ['japanese', 'Arigato', None, None, '1200 South Holden Road'],
 ['cafe', 'Arrowhead Coffee', None, None, '518 North Spring Street Ste D'],
 ['japanese', 'Asahi', None, None, '4520 West Market Street'],
 ['mexican', 'Ay mi Madre', None, None, '1614 Highwoods Boulevard Ste B'],
 ['cafe', 'Back Table', None, None, '816 South Elm Street Ste 1A'],
 ['american', "Bad Daddy's Burger Bar", None, None, '4522 West Wendover Avenue Ste 101'],
 ['vietnamese', 'BaoBao Kitchen', None, None, '2403 Battleground Avenue Ste 2'],
 ['pizza', "Bejta's Pizza and Subs", None, None, '109 Bonita Drive'],
 ['cafe', 'Bella Ciao', None, None, '3612-A Spring Garden Street'],
 ['cafe', 'Bellemeade Bistro', None, None, '300 North Greene Street Ste 195'],
 ['american', 'Big Burger Spot', None, None, '3750 Battleground Avenue Ste A'],
 ['pizza', 'Blaze Pizza', None, None, '4522 West Wendover Avenue Ste 110'],
 ['cafe', 'Blendology', None, None, '112 North Elm Street'],
 ['pizza', 'Blue Rock Pizza & Tap', None, None, '5710 West Gate City Boulevard'],
 ['cafe', 'Boba Bee', None, None, '344 Tate Street'],
 ['cafe', 'Bobo Cafe', None, None, '1605 Westover Terrace'],
 ['american', 'Bon-Bon Wings & Grill', None, None, '3605 Groometown Road'],
 ['cafe', 'Borough Coffee', None, None, '204 North Mendenhall Street'],
 ['cafe', 'Brewed & Bottled', None, None, '4113 Lawndale Drive Ste 107'],
 ['cafe', 'Bubble Bear', None, None, '3343 Battleground Avenue'],
 ['mexican', 'Burrito Shak', None, None, '4016 Battleground Avenue Ste D'],
 ['cafe', 'Cafe Bom Bom', None, None, '4929 West Market Street Ste 2102'],
 ['italian', 'Cafe Pasta & Grille', None, None, '305 State Street'],
 ['mexican', 'California Burritos Express', None, None, '2408 Spring Garden Street Ste D'],
 ['mexican', 'Casa Vallarta Mexican and Seafood Grill', None, None, '3915 Battleground Avenue'],
 ['cafe', 'Cheesecakes by Alex', None, None, '315 South Elm Street'],
 ['korean', 'Chicken Bee', None, None, '4927 West Market Street Ste 3102'],
 ['chinese', 'China Buffet', None, None, '4310 Big Tree Way'],
 ['chinese', 'China Cafe', None, None, '2408-A Spring Garden Street'],
 ['chinese', 'China Garden', None, None, '3207 South Holden Road'],
 ['chinese', 'China Wok', None, None, '3605 Groometown Road Ste 115'],
 ['chinese', "China's Best", None, None, '2142 Lawndale Drive'],
 ['barbecue', 'City Barbeque', None, None, '2647 Lawndale Drive'],
 ['chinese', 'City Dragon', None, None, '5700 West Market Street'],
 ['cafe', 'Coffee. Cameras. Creators', None, None, '225 Summit Avenue'],
 ['cafe', 'Coffeeology', None, None, '423 Tate Street Ste A'],
 ['cafe', 'Coliseum Cafe', None, None, '1904 Coliseum Boulevard'],
 ['cafe', 'Common Grounds', None, None, '602 South Elam Avenue'],
 ['mexican', 'Crazy Mexico', None, None, '332 Tate Street'],
 ['cafe', 'Crooked Tail Cat Cafe', None, None, '604 South Elm Street'],
 ['pizza', 'Crust & Craft', None, None, '1424 Westover Terrace'],
 ['pizza', 'Cugino Forno', None, None, '1160 Revolution Mill Drive'],
 ['mexican', 'Culichi', None, None, '3025 West Gate City Boulevard'],
 ['caribbean', 'Da Reggae Cafe', None, None, '2528 West Gate City Boulevard'],
 ['caribbean', "Da'Jerk Machine", None, None, '7 Corporate Center Court Ste B'],
 ['korean', 'Danji Korean Restaurant', None, None, '4929 West Market Street Ste 2104'],
 ['cafe', 'Delicious Bakery', None, None, '1209 Battleground Avenue Ste 100'],
 ['cafe', 'Dolce Aroma Coffee & Wine Bar', None, None, '201 North Elm Street Ste 122'],
 ['japanese', 'Don', None, None, '423 Tate Street Ste B'],
 ['american', 'East Coast Wings & Grill', None, None, '338 Tate Street'],
 ['mexican', 'El Mercadito', None, None, '103 Muirs Chapel Road'],
 ['pizza', "Elizabeth's Pizza", None, None, '3607 Groometown Road'],
 ['american', 'Embur Fire Fusion', None, None, '107 Smyres Place'],
 ['mexican', 'Empanada Grill', None, None, '5705 Inman Road'],
 ['american', 'Epic Chophouse', None, None, '301 Pisgah Church Road Ste F'],
 ['american', "Fat Dog's Grille & Pub", None, None, '3021 Spring Garden Street'],
 ['cafe', 'Fig & Olive Cafe', None, None, '4507 West Market Street'],
 ['seafood', 'Fishbones', None, None, '2119 Walker Avenue'],
 ['korean', 'Flame Broiler', None, None, '3606 North Elm Street Ste H'],
 ['japanese', 'Fuji Asian Food Express', None, None, '1575 New Garden Road'],
 ['japanese', 'Fuji Sushi Hibachi', None, None, '433 Pisgah Church Road'],
 ['american', "Funderburk's", None, None, '2714 North Church Street Ste D'],
 ['mediterranean', "Ghassan's Fresh Mediterranean Eats", None, None, '400 East Cornwallis Drive'],
 ['japanese', 'Ginza Steakhouse', None, None, '2807 Groometown Road'],
 ['american', "Glonda's Homestyle", None, None, '4925 West Market Street Ste 1136'],
 ['chinese', 'Golden Dragon', None, None, '2921 Battleground Avenue Ste B'],
 ['pizza', 'Golden Pizza & Subs', None, None, '2278 Golden Gate Drive'],
 ['chinese', 'Golden Wok', None, None, '1216 Bridford Parkway Ste N'],
 ['chinese', 'Gourmet China', None, None, '3709F Battleground Avenue'],
 ['cafe', "Green Joe's", None, None, '2915 Battleground Avenue Ste A'],
 ['breakfast', "Greenfield's NY Deli and Bagels", None, None, '2130 New Garden Road Ste G'],
 ['cafe', 'Greenleaf Coffee Co-Op', None, None, '5800 West Friendly Avenue'],
 ['american', "Grey's Tavern", None, None, '343 South Elm Street'],
 ['mexican', 'Guisados Homestyle Grill', None, None, '5700 West Market Street Ste F'],
 ['japanese', 'Happy Bowl', None, None, '1201 West Gate City Boulevard Ste 102'],
 ['japanese', 'Hibachi Cafe', None, None, '362 South Elm Street'],
 ['japanese', 'Hibachi Fusion', None, None, '2715A Grandview Avenue'],
 ['japanese', 'Hoba Sushi & Hibachi', None, None, '3706 Elmsley Court Ste 101'],
 ['japanese', 'Hokkaido Ramen & Sushi', None, None, '6010 Landmark Center Boulevard'],
 ['cafe', 'Home Grounds', None, None, '405 State Street'],
 ['pizza', 'HomeSlice Pizza & Subs', None, None, '2223 Flemming Road'],
 ['japanese', 'Ichiban Grill Supreme Buffet', None, None, '3020 West Gate City Boulevard'],
 ['latin', 'Ilobasco Restaurante & Pupuseria', None, None, '3008 West Gate City Boulevard'],
 ['chinese', 'Jade Express', None, None, '337 West Wendover Avenue Ste B'],
 ['american', "Jake's Diner", None, None, '2206 South Holden Road'],
 ['american', 'Jams Deli', None, None, '5707 West Friendly Avenue'],
 ['pizza', "Jesse's Catering & Lakeside Grill", None, None, '5040 Bass Chapel Road'],
 ['japanese', 'Kabuto Japanese Steakhouse and Sushi Bar', None, None, '1617 Stanley Road'],
 ['american', 'Kau', None, None, '2003 Yanceyville Street'],
 ['japanese', 'Kazoku Sushi & Bar', None, None, '948 Walker Avenue Ste B'],
 ['mexican', 'Kiosco Mexican Grill', None, None, '3011 Spring Garden Street Ste A'],
 ['japanese', 'Kobe Grill', None, None, '3712 Lawndale Drive Ste K'],
 ['japanese', 'Kobe of Japan', None, None, '1216 Bridford Parkway Ste F'],
 ['mexican', 'La Azteca #2 Carnitas Barbacoa', None, None, '3737 Farmington Drive'],
 ['mexican', 'La Bamba Mexican Restaurant', None, None, '601 State Street'],
 ['mexican', 'La Costenita', None, None, '4631 West Market Street'],
 ['mexican', 'La Hacienda Mexican Restaurant', None, None, '1218-E Bridford Parkway'],
 ['cafe', 'Latitud Coffee Co.', None, None, '230 South Elm Street Ste A'],
 ['latin', 'Leblon Churrascaria', None, None, '106 South Holden Road'],
 ['indian', 'Lemon Indian Cuisine', None, None, '1568 Highwoods Boulevard'],
 ['japanese', "Little Ari's", None, None, '4129 Spring Garden Street'],
 ['cafe', 'Littleftoot Matcha Cafe', None, None, '1101 West Gate City Boulevard Ste 203'],
 ['mexican', "Los Chico's Mexican Restaurant", None, None, '200 South Elm Street'],
 ['mexican', 'Los Koras', None, None, '3021 Randleman Road'],
 ['barbecue', "Mac's Speed Shop", None, None, '1218 Battleground Avenue'],
 ['cafe', "Manny's Cafe & Smoothies", None, None, '321 Martin Luther King Jr Drive'],
 ['pizza', "Mario's Pizza", None, None, '4215 West Wendover Avenue'],
 ['american', 'Mayberry Ice Cream & Sandwich Shop', None, None, '946 Summit Avenue'],
 ['seafood', 'Mayflower Seafood', None, None, '2631 Randleman Road'],
 ['mexican', 'Mexico Restaurant', None, None, '4800 West Market Street'],
 ['mexican', 'Mezcali Mexican Restaurant', None, None, '2270 Golden Gate Drive'],
 ['japanese', 'Midori Express', None, None, '2421 Randleman Road'],
 ['japanese', 'Mizumi Hibachi and Sushi', None, None, '309 State Street'],
 ['mexican', 'Monterrey Mexican Restaurant', None, None, '3724 Battleground Avenue Ste L'],
 ['japanese', 'Mr. Kirin Japanese Kitchen', None, None, '2920 Martinsville Road Ste F'],
 ['japanese', 'Mr. Tokyo', None, None, '3015 West Gate City Boulevard'],
 ['mediterranean', 'Mythos Grill', None, None, '3900 West Market Street'],
 ['japanese', 'Nagoya Japan', None, None, '2209 Flemming Road'],
 ['mediterranean', 'Nazareth Bread Co. & Restaurant', None, None, '4507 West Market Street'],
 ['pizza', 'New York Pizza', None, None, '337 Tate Street'],
 ['cafe', 'No Rush', None, None, '245 East Friendly Avenue Ste 103'],
 ['indian', 'Noor Kitchen & Cocktails', None, None, '4312 Big Tree Way'],
 ['italian', 'North Italia', None, None, '610 Pembroke Road'],
 ['cafe', 'Northern Roots Coffeehouse', None, None, '300 South Elm Street Ste B'],
 ['pizza', 'Nostra Pizza & Italian Restaurant', None, None, '3900 West Market Street Ste B'],
 ['pizza', 'NY Pizza', None, None, '2704 Battleground Avenue'],
 ['chinese', 'One Wok Chinese Grill', None, None, '5803 Hunt Club Road Ste E'],
 ['pizza', 'Palermo Pizza', None, None, '5700 West Market Street'],
 ['american', 'Pantry Fried Chicken', None, None, '1040 West Gate City Boulevard'],
 ['vietnamese', 'Paris Bánh Mì', None, None, '2703 West Gate City Boulevard Ste G'],
 ['italian', 'Pastabilities', None, None, '1726 Battleground Avenue'],
 ['mediterranean', 'Pita Delight', None, None, '617 Friendly Center Road'],
 ['mediterranean', 'Pita Delite', None, None, '1101 West Gate City Boulevard'],
 ['mediterranean', 'Pita Press', None, None, '301 Pisgah Church Road Ste B'],
 ['pizza', "Pizzeria L'Italiano", None, None, '219 South Elm Street Ste B'],
 ['mexican', "Poblano's Mexican Bar & Grill", None, None, '5710 West Gate City Boulevard'],
 ['american', 'Porter House Burger Co', None, None, '1637 New Garden Road'],
 ['barbecue', 'Qinji Hawaiian BBQ & Ramen', None, None, '2224 Golden Gate Drive'],
 ['pizza', "Queen's Pizza & Subs", None, None, '2505 Carroll Street Ste B'],
 ['cafe', "Rachel's Rose Cottage", None, None, '813 Quadrangle Drive'],
 ['seafood', 'Red Crab', None, None, '3017 West Gate City Boulevard'],
 ['seafood', 'Reel Seafood Grill', None, None, '2002 New Garden Road Ste 208'],
 ['american', "Rico's Subs & Tacos", None, None, '4925 West Market Street'],
 ['mexican', 'Rio Grande', None, None, '1635 New Garden Road'],
 ['american', "Rody's Tavern", None, None, '5105 Michaux Road'],
 ['american', "Ruth's Chris Steak House", None, None, '800 Green Valley Road Ste 100'],
 ['african', 'Saint Louis Saveurs', None, None, '1608 West Friendly Avenue'],
 ['italian', 'Salvino Cucina Italiana', None, None, '2917 Battleground Avenue Ste D'],
 ['mexican', 'San Luis', None, None, '1503 West Gate City Boulevard'],
 ['mexican', 'Santa Fe Mexican Grill', None, None, '423 Pisgah Church Road'],
 ['japanese', 'Sapporo Fantasy Japanese Steak', None, None, '2939 Battleground Avenue Ste C'],
 ['breakfast', 'Scrambled Southern Diner', None, None, '2417 Spring Garden Street'],
 ['american', 'Scratch Fried Chicken', None, None, '1220 Battleground Avenue Ste A'],
 ['indian', 'Shukkranaa Indian Cuisine', None, None, '500 Americhase Drive Ste H'],
 ['cafe', 'Sip Lab', None, None, '1603 Battleground Avenue Ste A'],
 ['pizza', 'Slices By Tony', None, None, '401 Tate Street'],
 ['mexican', 'Solo Taco', None, None, '2005 Yanceyville Street Ste 112'],
 ['cafe', 'Somoora Cafe', None, None, '5340 West Market Street'],
 ['vietnamese', 'Song Que Restaurant', None, None, '2201 Merritt Drive'],
 ['cafe', 'Spring Garden Bakery & Cafe', None, None, '7011 Albert Pick Road Ste A'],
 ['cafe', 'Spring Garden Bakery and Coffeehouse', None, None, '1932 Spring Garden Street'],
 ['pizza', 'Sticks and Stones', None, None, '2200 Walker Avenue'],
 ['american', 'Sub Spot', None, None, '3709 Battleground Avenue Ste D'],
 ['indian', 'Taaza Indian Bistro', None, None, '1216-M Bridford Parkway'],
 ['mexican', 'Taco in the Box', None, None, '3204 East Bessemer Avenue'],
 ['mexican', 'Taco Mama', None, None, '2168 Lawndale Drive'],
 ['chinese', 'Takara Noodle', None, None, '948 Walker Avenue Ste D'],
 ['japanese', 'Tampopo Ramen & Hibachi', None, None, '4929 West Market Street Ste 2107'],
 ['mexican', 'Taqueria El Azteca Mexican Grill', None, None, '5605 West Friendly Avenue Ste B'],
 ['cafe', 'Tate Street Coffee', None, None, '334 Tate Street'],
 ['cafe', 'Tea Lala Snow & Tea', None, None, '3808 West Gate City Boulevard Ste H'],
 ['american', "Tex & Shirley's", None, None, '1617 West Friendly Avenue'],
 ['thai', 'Thai Chiang Mai', None, None, '500 Americhase Drive Ste C'],
 ['thai', 'Thai Corner Kitchen', None, None, '3741 Battleground Avenue Ste B'],
 ['thai', 'Thai Square', None, None, '3361 Battleground Avenue'],
 ['seafood', "The Captain's Catch", None, None, '4637 West Market Street Ste B'],
 ['pizza', 'The Corner Slice', None, None, '600 North Elm Street'],
 ['italian', 'The Pavilion Restaurant', None, None, '2010 West Vandalia Road'],
 ['italian', 'Times Square Pizza', None, None, '101 Elmsley Meadows Lane'],
 ['pizza', "Tito's Pizza", None, None, '2700 West Gate City Boulevard'],
 ['japanese', 'Tokyo Express', None, None, '3722 Battleground Avenue Ste F'],
 ['japanese', 'Tokyo Grill', None, None, '2631 Lawndale Drive'],
 ['japanese', "Toshi's Café", None, None, '5710 West Gate City Boulevard'],
 ['cafe', 'Union Coffee Co', None, None, '216 West Friendly Avenue'],
 ['japanese', 'US Sushi', None, None, '619 Friendly Center Road'],
 ['vietnamese', 'Van Loi II', None, None, '3829 West Gate City Boulevard Ste D'],
 ['mexican', "Vaquero's Mexican Grill", None, None, '3738 West Gate City Boulevard Ste A'],
 ['cafe', 'Vignette Coffee', None, None, '5715 West Market Street Ste E'],
 ['italian', 'Villa Italian', None, None, '3712 Lawndale Drive Ste A'],
 ['american', 'Village Tavern', None, None, '1903 Westridge Road'],
 ['italian', "Vino's Italian Cuisine", None, None, '1629 Stanley Road'],
 ['italian', "Vito's Italian Restaurant", None, None, '2258 Golden Gate Drive'],
 ['peruvian', 'Viva Chicken', None, None, '4520 West Wendover Avenue Ste 110'],
 ['american', "Walk-On's Sports Bistreaux", None, None, '4505 Landover Road'],
 ['american', 'Wallstreet Deli & Catering', None, None, '7327 West Friendly Avenue Ste A'],
 ['american', 'Wings & Grill', None, None, '709 East Market Street Ste 200'],
 ['american', 'Yum Yum', None, None, '1219 Spring Garden Street'],
 ['mediterranean', 'ZeeYum Kitchen', None, None, '4612 West Market Street Ste A']]

listing_sources = {'Bonchon Greensboro': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Seoul Garden Restaurant': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'KPOT Korean BBQ & Hot Pot': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Pho Hien Vuong Vietnamese Restaurant': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Saigon Cuisine Restaurant': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Banh Mi Saigon Vietnamese Sandwiches': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'JakJin Bistro Pho & More': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Saffron Indian Cuisine': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Raaz Indian Kitchen': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Agni Indian Restaurant and Bar': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Bangkok Cafe': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Jerusalem Market on Elm': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Zaytoon Mediterranean Grill': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 "Aladdin's Shawarma": 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Inka Peruvian Grill': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Chez Genèse': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Blue Denim': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Undercurrent Restaurant': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'White and Wood': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Machete': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'The Sage Mule': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 "Dear Dad's": 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Natty Greene’s Pub & Brewing Co.': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Yokai': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 "Midori's Japanese Hibachi": 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Mellow Mushroom': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Chandler’s': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Awoo Coffee': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Pangaea Bistro & Bar': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'CharBar No. 7': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 '1618 West Seafood Grille': 'https://www.openstreetmap.org/node/8505414391',
 '33 & Elm Coffee House': 'https://www.openstreetmap.org/node/13257879625',
 '42 Fry': 'https://www.openstreetmap.org/node/13535247648',
 '7 Brew': 'https://www.openstreetmap.org/node/13621988655',
 'A Special Blend': 'https://www.openstreetmap.org/node/9797014025',
 'Achilles Grill': 'https://www.openstreetmap.org/node/8427449583',
 'Acropolis': 'https://www.openstreetmap.org/node/14242387595',
 'Akoko': 'https://www.openstreetmap.org/node/13305701131',
 'Apple China': 'https://www.openstreetmap.org/node/2695795406',
 'Arigato': 'https://www.openstreetmap.org/node/4645058682',
 'Arrowhead Coffee': 'https://www.openstreetmap.org/node/12178896325',
 'Asahi': 'https://www.openstreetmap.org/node/13143512896',
 'Ay mi Madre': 'https://www.openstreetmap.org/node/10297582504',
 'Back Table': 'https://www.openstreetmap.org/node/13244850452',
 "Bad Daddy's Burger Bar": 'https://www.openstreetmap.org/node/6371094705',
 'BaoBao Kitchen': 'https://www.openstreetmap.org/node/8427449581',
 "Bejta's Pizza and Subs": 'https://www.openstreetmap.org/node/13266020441',
 'Bella Ciao': 'https://www.openstreetmap.org/node/13461498551',
 'Bellemeade Bistro': 'https://www.openstreetmap.org/node/14052195803',
 'Big Burger Spot': 'https://www.openstreetmap.org/node/3297169179',
 'Blaze Pizza': 'https://www.openstreetmap.org/node/11881362069',
 'Blendology': 'https://www.openstreetmap.org/node/13915017919',
 'Blue Rock Pizza & Tap': 'https://www.openstreetmap.org/node/13649901347',
 'Boba Bee': 'https://www.openstreetmap.org/node/13462269981',
 'Bobo Cafe': 'https://www.openstreetmap.org/node/13059991929',
 'Bon-Bon Wings & Grill': 'https://www.openstreetmap.org/node/5487457132',
 'Borough Coffee': 'https://www.openstreetmap.org/node/11878744031',
 'Brewed & Bottled': 'https://www.openstreetmap.org/node/13123418668',
 'Bubble Bear': 'https://www.openstreetmap.org/node/11773749211',
 'Burrito Shak': 'https://www.openstreetmap.org/node/13255172621',
 'Cafe Bom Bom': 'https://www.openstreetmap.org/node/12090574281',
 'Cafe Pasta & Grille': 'https://www.openstreetmap.org/node/13175638279',
 'California Burritos Express': 'https://www.openstreetmap.org/node/13095304349',
 'Casa Vallarta Mexican and Seafood Grill': 'https://www.openstreetmap.org/node/13349016905',
 'Cheesecakes by Alex': 'https://www.openstreetmap.org/way/208194313',
 'Chicken Bee': 'https://www.openstreetmap.org/node/11979206559',
 'China Buffet': 'https://www.openstreetmap.org/node/6483239060',
 'China Cafe': 'https://www.openstreetmap.org/node/8447348019',
 'China Garden': 'https://www.openstreetmap.org/node/4108900442',
 'China Wok': 'https://www.openstreetmap.org/node/5487457133',
 "China's Best": 'https://www.openstreetmap.org/node/5788900521',
 'City Barbeque': 'https://www.openstreetmap.org/node/11774144077',
 'City Dragon': 'https://www.openstreetmap.org/node/12516743256',
 'Coffee. Cameras. Creators': 'https://www.openstreetmap.org/node/14040469190',
 'Coffeeology': 'https://www.openstreetmap.org/node/1663832232',
 'Coliseum Cafe': 'https://www.openstreetmap.org/node/6465992480',
 'Common Grounds': 'https://www.openstreetmap.org/node/11343801656',
 'Crazy Mexico': 'https://www.openstreetmap.org/node/12729860572',
 'Crooked Tail Cat Cafe': 'https://www.openstreetmap.org/node/10296269312',
 'Crust & Craft': 'https://www.openstreetmap.org/node/13571590611',
 'Cugino Forno': 'https://www.openstreetmap.org/node/11532553945',
 'Culichi': 'https://www.openstreetmap.org/node/3413154903',
 'Da Reggae Cafe': 'https://www.openstreetmap.org/node/6466023808',
 "Da'Jerk Machine": 'https://www.openstreetmap.org/node/13439949065',
 'Danji Korean Restaurant': 'https://www.openstreetmap.org/node/12064930524',
 'Delicious Bakery': 'https://www.openstreetmap.org/node/7089932308',
 'Dolce Aroma Coffee & Wine Bar': 'https://www.openstreetmap.org/node/11773923582',
 'Don': 'https://www.openstreetmap.org/node/8505414415',
 'East Coast Wings & Grill': 'https://www.openstreetmap.org/node/8505414408',
 'El Mercadito': 'https://www.openstreetmap.org/node/12511122653',
 "Elizabeth's Pizza": 'https://www.openstreetmap.org/node/3418334069',
 'Embur Fire Fusion': 'https://www.openstreetmap.org/node/12958341080',
 'Empanada Grill': 'https://www.openstreetmap.org/node/13228723843',
 'Epic Chophouse': 'https://www.openstreetmap.org/node/14241101798',
 "Fat Dog's Grille & Pub": 'https://www.openstreetmap.org/node/6501252965',
 'Fig & Olive Cafe': 'https://www.openstreetmap.org/node/12569144119',
 'Fishbones': 'https://www.openstreetmap.org/node/11346695889',
 'Flame Broiler': 'https://www.openstreetmap.org/node/13093255335',
 'Fuji Asian Food Express': 'https://www.openstreetmap.org/node/3480333111',
 'Fuji Sushi Hibachi': 'https://www.openstreetmap.org/node/13408720225',
 "Funderburk's": 'https://www.openstreetmap.org/node/13644031994',
 "Ghassan's Fresh Mediterranean Eats": 'https://www.openstreetmap.org/node/12544992165',
 'Ginza Steakhouse': 'https://www.openstreetmap.org/node/8455851491',
 "Glonda's Homestyle": 'https://www.openstreetmap.org/node/13643815473',
 'Golden Dragon': 'https://www.openstreetmap.org/node/5491476443',
 'Golden Pizza & Subs': 'https://www.openstreetmap.org/node/13370793920',
 'Golden Wok': 'https://www.openstreetmap.org/node/3422225276',
 'Gourmet China': 'https://www.openstreetmap.org/node/11534281131',
 "Green Joe's": 'https://www.openstreetmap.org/node/11146941838',
 "Greenfield's NY Deli and Bagels": 'https://www.openstreetmap.org/node/11832951597',
 'Greenleaf Coffee Co-Op': 'https://www.openstreetmap.org/node/1663832270',
 "Grey's Tavern": 'https://www.openstreetmap.org/node/2185202818',
 'Guisados Homestyle Grill': 'https://www.openstreetmap.org/node/13126338142',
 'Happy Bowl': 'https://www.openstreetmap.org/node/9041811238',
 'Hibachi Cafe': 'https://www.openstreetmap.org/node/3314317054',
 'Hibachi Fusion': 'https://www.openstreetmap.org/node/6418555694',
 'Hoba Sushi & Hibachi': 'https://www.openstreetmap.org/node/13088118581',
 'Hokkaido Ramen & Sushi': 'https://www.openstreetmap.org/node/12377322824',
 'Home Grounds': 'https://www.openstreetmap.org/node/13341149634',
 'HomeSlice Pizza & Subs': 'https://www.openstreetmap.org/node/13036485928',
 'Ichiban Grill Supreme Buffet': 'https://www.openstreetmap.org/node/6466023810',
 'Ilobasco Restaurante & Pupuseria': 'https://www.openstreetmap.org/node/7099039032',
 'Jade Express': 'https://www.openstreetmap.org/node/13617740900',
 "Jake's Diner": 'https://www.openstreetmap.org/node/1703831881',
 'Jams Deli': 'https://www.openstreetmap.org/node/6606218293',
 "Jesse's Catering & Lakeside Grill": 'https://www.openstreetmap.org/node/12152232226',
 'Kabuto Japanese Steakhouse and Sushi Bar': 'https://www.openstreetmap.org/node/3413154809',
 'Kau': 'https://www.openstreetmap.org/node/12877078020',
 'Kazoku Sushi & Bar': 'https://www.openstreetmap.org/node/13420006848',
 'Kiosco Mexican Grill': 'https://www.openstreetmap.org/node/3418210499',
 'Kobe Grill': 'https://www.openstreetmap.org/node/8501744793',
 'Kobe of Japan': 'https://www.openstreetmap.org/node/3422225278',
 'La Azteca #2 Carnitas Barbacoa': 'https://www.openstreetmap.org/node/12879410938',
 'La Bamba Mexican Restaurant': 'https://www.openstreetmap.org/node/6146856915',
 'La Costenita': 'https://www.openstreetmap.org/node/12366138034',
 'La Hacienda Mexican Restaurant': 'https://www.openstreetmap.org/node/3422225280',
 'Latitud Coffee Co.': 'https://www.openstreetmap.org/node/12996466556',
 'Leblon Churrascaria': 'https://www.openstreetmap.org/node/6418555700',
 'Lemon Indian Cuisine': 'https://www.openstreetmap.org/node/11835044287',
 "Little Ari's": 'https://www.openstreetmap.org/node/12064881159',
 'Littleftoot Matcha Cafe': 'https://www.openstreetmap.org/node/14122736558',
 "Los Chico's Mexican Restaurant": 'https://www.openstreetmap.org/node/12996456131',
 'Los Koras': 'https://www.openstreetmap.org/node/8498328565',
 "Mac's Speed Shop": 'https://www.openstreetmap.org/node/7099039005',
 "Manny's Cafe & Smoothies": 'https://www.openstreetmap.org/node/13599720159',
 "Mario's Pizza": 'https://www.openstreetmap.org/node/3416078761',
 'Mayberry Ice Cream & Sandwich Shop': 'https://www.openstreetmap.org/node/13026918090',
 'Mayflower Seafood': 'https://www.openstreetmap.org/node/8498359819',
 'Mexico Restaurant': 'https://www.openstreetmap.org/node/4496078030',
 'Mezcali Mexican Restaurant': 'https://www.openstreetmap.org/node/13046593176',
 'Midori Express': 'https://www.openstreetmap.org/node/8498359865',
 'Mizumi Hibachi and Sushi': 'https://www.openstreetmap.org/node/13175629353',
 'Monterrey Mexican Restaurant': 'https://www.openstreetmap.org/node/13007487359',
 'Mr. Kirin Japanese Kitchen': 'https://www.openstreetmap.org/node/13088031114',
 'Mr. Tokyo': 'https://www.openstreetmap.org/node/13196770480',
 'Mythos Grill': 'https://www.openstreetmap.org/node/9797014028',
 'Nagoya Japan': 'https://www.openstreetmap.org/node/13540424289',
 'Nazareth Bread Co. & Restaurant': 'https://www.openstreetmap.org/node/12568919747',
 'New York Pizza': 'https://www.openstreetmap.org/node/8505414407',
 'No Rush': 'https://www.openstreetmap.org/node/14167928073',
 'Noor Kitchen & Cocktails': 'https://www.openstreetmap.org/node/13226864125',
 'North Italia': 'https://www.openstreetmap.org/node/13009258807',
 'Northern Roots Coffeehouse': 'https://www.openstreetmap.org/node/11881823774',
 'Nostra Pizza & Italian Restaurant': 'https://www.openstreetmap.org/node/9797014024',
 'NY Pizza': 'https://www.openstreetmap.org/way/324238130',
 'One Wok Chinese Grill': 'https://www.openstreetmap.org/node/13226908920',
 'Palermo Pizza': 'https://www.openstreetmap.org/node/9531448275',
 'Pantry Fried Chicken': 'https://www.openstreetmap.org/node/12609863709',
 'Paris Bánh Mì': 'https://www.openstreetmap.org/node/14071329123',
 'Pastabilities': 'https://www.openstreetmap.org/node/5788900503',
 'Pita Delight': 'https://www.openstreetmap.org/node/12610680690',
 'Pita Delite': 'https://www.openstreetmap.org/node/9041811235',
 'Pita Press': 'https://www.openstreetmap.org/node/14114555717',
 "Pizzeria L'Italiano": 'https://www.openstreetmap.org/node/8558519804',
 "Poblano's Mexican Bar & Grill": 'https://www.openstreetmap.org/node/2695800582',
 'Porter House Burger Co': 'https://www.openstreetmap.org/node/12091898793',
 'Qinji Hawaiian BBQ & Ramen': 'https://www.openstreetmap.org/node/11879197089',
 "Queen's Pizza & Subs": 'https://www.openstreetmap.org/node/8436110221',
 "Rachel's Rose Cottage": 'https://www.openstreetmap.org/node/12819293323',
 'Red Crab': 'https://www.openstreetmap.org/node/3413154908',
 'Reel Seafood Grill': 'https://www.openstreetmap.org/node/10297175273',
 "Rico's Subs & Tacos": 'https://www.openstreetmap.org/node/12064953038',
 'Rio Grande': 'https://www.openstreetmap.org/node/11926991251',
 "Rody's Tavern": 'https://www.openstreetmap.org/node/12836802859',
 "Ruth's Chris Steak House": 'https://www.openstreetmap.org/node/7797912726',
 'Saint Louis Saveurs': 'https://www.openstreetmap.org/node/12648281397',
 'Salvino Cucina Italiana': 'https://www.openstreetmap.org/node/12762967762',
 'San Luis': 'https://www.openstreetmap.org/node/4151904944',
 'Santa Fe Mexican Grill': 'https://www.openstreetmap.org/node/11691248155',
 'Sapporo Fantasy Japanese Steak': 'https://www.openstreetmap.org/node/5491476431',
 'Scrambled Southern Diner': 'https://www.openstreetmap.org/node/8448325551',
 'Scratch Fried Chicken': 'https://www.openstreetmap.org/node/13108098815',
 'Shukkranaa Indian Cuisine': 'https://www.openstreetmap.org/node/13255172003',
 'Sip Lab': 'https://www.openstreetmap.org/node/13533393379',
 'Slices By Tony': 'https://www.openstreetmap.org/node/9173720823',
 'Solo Taco': 'https://www.openstreetmap.org/node/13895538268',
 'Somoora Cafe': 'https://www.openstreetmap.org/node/14104418161',
 'Song Que Restaurant': 'https://www.openstreetmap.org/node/14203533257',
 'Spring Garden Bakery & Cafe': 'https://www.openstreetmap.org/node/13526108360',
 'Spring Garden Bakery and Coffeehouse': 'https://www.openstreetmap.org/node/8448341735',
 'Sticks and Stones': 'https://www.openstreetmap.org/node/11343801657',
 'Sub Spot': 'https://www.openstreetmap.org/node/11795599722',
 'Taaza Indian Bistro': 'https://www.openstreetmap.org/node/6418555724',
 'Taco in the Box': 'https://www.openstreetmap.org/node/13104715818',
 'Taco Mama': 'https://www.openstreetmap.org/node/7099046684',
 'Takara Noodle': 'https://www.openstreetmap.org/node/12661006552',
 'Tampopo Ramen & Hibachi': 'https://www.openstreetmap.org/node/12512645476',
 'Taqueria El Azteca Mexican Grill': 'https://www.openstreetmap.org/node/6395012625',
 'Tate Street Coffee': 'https://www.openstreetmap.org/node/3257392599',
 'Tea Lala Snow & Tea': 'https://www.openstreetmap.org/node/8455851429',
 "Tex & Shirley's": 'https://www.openstreetmap.org/node/11396991331',
 'Thai Chiang Mai': 'https://www.openstreetmap.org/node/3297736448',
 'Thai Corner Kitchen': 'https://www.openstreetmap.org/node/4108860895',
 'Thai Square': 'https://www.openstreetmap.org/node/11899210375',
 "The Captain's Catch": 'https://www.openstreetmap.org/node/4496096671',
 'The Corner Slice': 'https://www.openstreetmap.org/node/6395111263',
 'The Pavilion Restaurant': 'https://www.openstreetmap.org/node/1703796269',
 'Times Square Pizza': 'https://www.openstreetmap.org/node/13457095287',
 "Tito's Pizza": 'https://www.openstreetmap.org/node/4168479593',
 'Tokyo Express': 'https://www.openstreetmap.org/node/13564287632',
 'Tokyo Grill': 'https://www.openstreetmap.org/node/12193161041',
 "Toshi's Café": 'https://www.openstreetmap.org/node/3878490696',
 'Union Coffee Co': 'https://www.openstreetmap.org/node/11635376899',
 'US Sushi': 'https://www.openstreetmap.org/node/4082287993',
 'Van Loi II': 'https://www.openstreetmap.org/node/4108844712',
 "Vaquero's Mexican Grill": 'https://www.openstreetmap.org/node/13046569486',
 'Vignette Coffee': 'https://www.openstreetmap.org/node/12001063669',
 'Villa Italian': 'https://www.openstreetmap.org/node/12315820210',
 'Village Tavern': 'https://www.openstreetmap.org/way/324235887',
 "Vino's Italian Cuisine": 'https://www.openstreetmap.org/node/6371072935',
 "Vito's Italian Restaurant": 'https://www.openstreetmap.org/node/6146854090',
 'Viva Chicken': 'https://www.openstreetmap.org/node/6371094704',
 "Walk-On's Sports Bistreaux": 'https://www.openstreetmap.org/node/14143463836',
 'Wallstreet Deli & Catering': 'https://www.openstreetmap.org/node/13091027698',
 'Wings & Grill': 'https://www.openstreetmap.org/node/13363915819',
 'Yum Yum': 'https://www.openstreetmap.org/way/311604522',
 'ZeeYum Kitchen': 'https://www.openstreetmap.org/node/12366185808'}
