"""PLATE Greensboro restaurant dataset.

Original student records are retained with their *historical, unverified* 1–5
price scores and ratings. New listings are directory-checked but have None for
unknown prices and ratings. None must NOT be represented as zero or five stars.
Records: [cuisine, name, price_score, rating, address].
Sources and verification scope: see DATA_NOTES.md.
"""
types = ['african',
 'american',
 'barbecue',
 'cafe',
 'chinese',
 'czech',
 'french',
 'german',
 'indian',
 'italian',
 'japanese',
 'korean',
 'mediterranean',
 'mexican',
 'peruvian',
 'pizza',
 'thai',
 'vegetarian',
 'vietnamese']

restaurant_data = [['american', 'Liberty Oak', '4', '4', '100 W Washington St'],
 ['japanese', 'Sushi Republic', '2', '4.5', '329 Tate St'],
 ['mediterranean', 'Sarahs Kabob Shop', '5', '5', '5340 W Market St'],
 ['mexican', 'Crafted - The Art of the Taco', '2', '4.5', '219 S Elm St'],
 ['pizza', 'Crafted - The Art of Pizza', '2', '4.5', '220 South Elm Street'],
 ['american', '1618 Downtown', '4.6', '3', '312 Elm St'],
 ['french', 'Print Works Bistro', '4.6', '4', '702 Green Valley Road'],
 ['american', 'Crafted - The Art of Street Food', '4.6', '2', '220 South Elm Street'],
 ['american', 'Lindley Park Filling Station', '4.6', '2', '2201 Walker Ave'],
 ['american', "Dame's Chicken & Waffles", '4.6', '1', '301 Martin Luther King Jr Dr'],
 ['american', "B. Christopher's Steakhouse", '4.5', '4', '201 North Elm Street'],
 ['mediterranean', 'Green Valley Grill', '4.5', '4', '622 Green Valley Road'],
 ['barbecue', 'Stamey’s Barbecue', '4.6', '3', '2812 Battleground Ave'],
 ['american', 'Hops Burger Bar', '4.6', '3', '2419 Spring Garden St'],
 ['thai', 'Taste of Thai', '4.4', '2', '1500 Mill St Ste 104'],
 ['indian', 'Dhanraj Emanuel Restaurant', '4.6', '2', '324 S Elm St'],
 ['italian', 'Osteria Italian Restaurant', '4.6', '4', '1310 Westover Ter Ste 111'],
 ['chinese', 'Phoenix Asian Cuisine', '4.3', '2', '1641 New Garden Rd Ste 111'],
 ['american', 'Emma Key’s Flat-Top Grill', '4.5', '2', '2206 Walker Ave'],
 ['cafe', 'Green Bean', '4.6', '2', '341 S Elm St'],
 ['american', 'Iron Hen Cafe', '4.5', '3', '908 Cridland Rd'],
 ['american', 'Darryls Wood Fired Grill', '4.6', '4', '3300 High Point Rd'],
 ['italian', 'Villa Rosa Italian Restaurant', '4.5', '3', '6019 W Market St'],
 ['american', 'The Old Town Draught House', '4.5', '2', '1205 Spring Garden St'],
 ['barbecue', 'Country BBQ', '4.4', '2', '4012 W Wendover Ave'],
 ['chinese', 'PF Chang’s', '4.4', '3', '3338 W Friendly Ave'],
 ['american', 'Biscuitville', '4.3', '1', '3011 Spring Garden St'],
 ['mexican', 'El Camino Real Mexican Grill', '4.3', '2', '413 Pisgah Church Rd'],
 ['korean', 'Bonchon Greensboro', None, None, '607 S Elm St'],
 ['korean', 'Seoul Garden Restaurant', None, None, '5318 W Market St Ste C'],
 ['korean', 'KPOT Korean BBQ & Hot Pot', None, None, '3011 W Gate City Blvd'],
 ['vietnamese', 'Pho Hien Vuong Vietnamese Restaurant', None, None, '4109 Spring Garden St'],
 ['vietnamese', 'Saigon Cuisine Restaurant', None, None, '4205 W Gate City Blvd'],
 ['vietnamese', 'Banh Mi Saigon Vietnamese Sandwiches', None, None, '3808 W Gate City Blvd'],
 ['vietnamese', 'JakJin Bistro Pho & More', None, None, '4414 Lawndale Dr Ste F'],
 ['indian', 'Saffron Indian Cuisine', None, None, '1500 Mill St Ste 104'],
 ['indian', 'Raaz Indian Kitchen', None, None, '427 Tate St'],
 ['indian', 'Agni Indian Restaurant and Bar', None, None, '651 S Regional Rd'],
 ['thai', 'Bangkok Cafe', None, None, '1203 S Holden Rd'],
 ['mediterranean', 'Jerusalem Market on Elm', None, None, '310 S Elm St'],
 ['mediterranean', 'Zaytoon Mediterranean Grill', None, None, '114 N Elm St'],
 ['mediterranean', "Aladdin's Shawarma", None, None, '5103 W Market St Ste A'],
 ['peruvian', 'Inka Peruvian Grill', None, None, '214 S Elm St'],
 ['french', 'Chez Genèse', None, None, '616 S Elm St'],
 ['american', 'Blue Denim', None, None, '217 S Elm St'],
 ['american', 'Undercurrent Restaurant', None, None, '327 Battleground Ave'],
 ['american', 'White and Wood', None, None, '215 S Elm St'],
 ['american', 'Machete', None, None, '600C Battleground Ave'],
 ['american', 'The Sage Mule', None, None, '608 Battleground Ave'],
 ['american', "Dear Dad's", None, None, '219 S Elm St'],
 ['american', 'Natty Greene’s Pub & Brewing Co.', None, None, '345 S Elm St'],
 ['japanese', 'Yokai', None, None, '501 N Greene St'],
 ['japanese', "Midori's Japanese Hibachi", None, None, '114 N Elm St'],
 ['pizza', 'Mellow Mushroom', None, None, '609 S Elm St'],
 ['cafe', 'Chandler’s', None, None, '341 S Elm St'],
 ['cafe', 'Awoo Coffee', None, None, '236 S Elm St'],
 ['american', 'Pangaea Bistro & Bar', None, None, '230 S Elm St'],
 ['american', 'CharBar No. 7', None, None, '3724 Lawndale Dr']]

listing_sources = {'Bonchon Greensboro': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Seoul Garden Restaurant': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'KPOT Korean BBQ & Hot Pot': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Pho Hien Vuong Vietnamese Restaurant': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Saigon Cuisine Restaurant': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Banh Mi Saigon Vietnamese Sandwiches': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'JakJin Bistro Pho & More': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Saffron Indian Cuisine': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Raaz Indian Kitchen': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Agni Indian Restaurant and Bar': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Bangkok Cafe': 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Jerusalem Market on Elm': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Zaytoon Mediterranean Grill': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 "Aladdin's Shawarma": 'https://www.visitgreensboronc.com/things-to-do/dining/',
 'Inka Peruvian Grill': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Chez Genèse': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Blue Denim': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Undercurrent Restaurant': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'White and Wood': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Machete': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'The Sage Mule': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 "Dear Dad's": 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Natty Greene’s Pub & Brewing Co.': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Yokai': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 "Midori's Japanese Hibachi": 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Mellow Mushroom': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Chandler’s': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Awoo Coffee': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'Pangaea Bistro & Bar': 'https://www.downtowngreensboro.org/explore/dining-drinks',
 'CharBar No. 7': 'https://www.visitgreensboronc.com/things-to-do/dining/'}
